#!/usr/bin/env node
const fs=require('fs'),path=require('path');
const input=process.argv[2],output=process.argv[3]||input,reportPath=process.argv[4];
if(!input){console.error('usage: node apply_readability_guard.js scene-deck.json [output.json] [report.json]');process.exit(2)}
const deck=JSON.parse(fs.readFileSync(input,'utf8'));
const operations=[],errors=[],warnings=[];
function textOf(e){return Array.isArray(e.runs)?e.runs.map(r=>String(r.text||'')).join(''):String(e.text||'')}
function visualChars(s){let n=0;for(const ch of String(s).replace(/\r/g,'')){if(ch==='\n'){n+=2;continue;}if(/\s/.test(ch)){n+=0.25;continue;}n += /[\x00-\x7F]/.test(ch)?0.58:1;}return n}
function capacity(e,size){const wpx=(Number(e.w)||0)*16,hpx=(Number(e.h)||0)*9,fpx=size*96/72;const lh=Number(e.style?.lineHeight||1.15);const cpl=Math.max(1,wpx/(fpx*0.92));const lines=Math.max(1,hpx/(fpx*lh));return cpl*lines*0.82}
function classify(e){const txt=textOf(e).trim(),y=Number(e.y||0);if(/^ED\d{2}-[A-Z]\s*\//.test(txt))return {role:'system_meta',min:8.5};if(y>=88||/^(※|注[:：]?|出典[:：]?|Source[:：]?|SOURCE[:：]?|n\s*=|N\s*=)/.test(txt))return {role:'footnote',min:9.5};const letters=txt.replace(/[^A-Za-z]/g,'');if(txt&&txt.length<=40&&letters&&letters.toUpperCase()===letters&&y<20)return {role:'kicker',min:10};if(txt.length<=18&&!txt.includes('\n'))return {role:'content_label',min:12};return {role:'body',min:14};}
for(const slide of deck.slides||[]){let slideChars=0,contentBoxes=0;for(const [idx,e] of (slide.elements||[]).entries()){if(e.type!=='text')continue;e.style=e.style||{};const txt=textOf(e).trim(),size=Number(e.style.fontSize||18),id=e.id||`text#${idx+1}`,c=classify(e),target=c.min;if(c.role==='content_label'||c.role==='body'){slideChars+=visualChars(txt);contentBoxes++;}if(size<target){const ratio=txt?visualChars(txt)/capacity(e,target):0;if(ratio>1.25){errors.push({slide:slide.id,element:id,code:'readability_requires_editorial_reflow',role:c.role,fromPt:size,targetPt:target,loadRatio:+ratio.toFixed(3),text:txt,recommended:['shorten_copy','change_pattern','split_page','move_detail_to_appendix']});}else{e.style.fontSize=target;operations.push({slide:slide.id,element:id,action:'raise_readability_floor',role:c.role,fromPt:size,toPt:target,projectedLoad:+ratio.toFixed(3),text:txt});}}const finalSize=Number(e.style.fontSize||18);if((c.role==='content_label'||c.role==='body')&&txt){const ratio=visualChars(txt)/capacity(e,finalSize);if(ratio>1.25)errors.push({slide:slide.id,element:id,code:'readability_density_overload',role:c.role,loadRatio:+ratio.toFixed(3),text:txt,recommended:['shorten_copy','change_pattern','split_page']});else if(ratio>1.05)warnings.push({slide:slide.id,element:id,code:'readability_tight_box',role:c.role,loadRatio:+ratio.toFixed(3),text:txt});}}
if(slideChars>520)warnings.push({slide:slide.id,code:'high_slide_text_density',visualChars:+slideChars.toFixed(1),recommended:['shorten_copy','diagram_first','split_page','appendix']});if(contentBoxes>18)warnings.push({slide:slide.id,code:'many_content_text_boxes',count:contentBoxes,recommended:['simplify_labels','merge_structure','diagram_first']});}
const report={profile:'READABILITY-GUARD-v1',file:input,output,policy:{systemMetaMinPt:8.5,kickerMinPt:10,footnoteMinPt:9.5,contentLabelMinPt:12,bodyMinPt:14,slideTextDensityWarningVisualChars:520},operations,errors,warnings,pass:errors.length===0};
if(reportPath){fs.mkdirSync(path.dirname(reportPath),{recursive:true});fs.writeFileSync(reportPath,JSON.stringify(report,null,2),'utf8')}
if(errors.length){console.error(`FAIL: ${errors.length} readability errors; no output written`);for(const x of errors)console.error(`${x.slide} ${x.element||'-'} ${x.code}`);process.exit(1)}
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(deck,null,2),'utf8');console.log(`PASS: ${operations.length} readability fixes / ${warnings.length} warnings -> ${output}`);
