#!/usr/bin/env node
const fs=require('fs');
const planPath=process.argv[2], output=process.argv[3]||'/mnt/data/content-plan-review.html';
if(!planPath){console.error('usage: node build_content_plan_review_html.js content-plan.json [output.html]');process.exit(2)}
const p=JSON.parse(fs.readFileSync(planPath,'utf8'));
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const slideCards=p.slides.map(s=>`<article class="card ${s.status}"><header><span>${esc(s.id)} / ${esc(s.role)}</span><b>${esc(s.status)}</b></header><h2>${esc(s.primaryMessage)}</h2><div class="visual"><strong>${esc(s.visual?.type||'none')}</strong><span>${esc(s.visual?.patternHint||'')}</span></div><div class="cols"><section><h3>EVIDENCE</h3>${(s.evidence||[]).map(e=>`<div class="ev"><b>${esc(e.title)}</b><p>${esc(e.message)}</p><small>${esc((e.sourceRefs||[]).join(' / '))}</small></div>`).join('')||'<p class="muted">No grounded evidence</p>'}</section><section><h3>ALTERNATIVES</h3>${(s.alternatives||[]).map(a=>`<div class="alt">${esc(a.kind)} / ${esc(a.title)} <span>${esc(a.visual||'')} ${a.score??''}</span></div>`).join('')||'<p class="muted">—</p>'}</section></div><footer>confidence ${(Number(s.confidence||0)*100).toFixed(0)}% ${s.warnings?.length?'• '+esc(s.warnings.join(' / ')):''}</footer></article>`).join('');
const catalog=(p.candidateCatalog||[]).map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.kind)}</td><td>${esc(c.title)}</td><td>${esc(c.visual)}</td><td>${c.supported?'yes':'no'}</td><td>${(Number(c.quality||0)*100).toFixed(0)}%</td><td>${esc((c.sourceRefs||[]).join(' / '))}</td></tr>`).join('');
const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Content Planner Review</title><style>body{margin:0;background:#eee9df;color:#111;font-family:Inter,"Noto Sans JP","Yu Gothic",sans-serif}main{max-width:1500px;margin:auto;padding:22px}.hero{background:#111;color:#fff;padding:28px;border:3px solid #111}.hero h1{font-size:52px;line-height:.95;margin:6px 0 12px}.hero p{max-width:950px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.card{background:#fffdf7;border:3px solid #111;padding:18px}.card header{display:flex;justify-content:space-between;font-size:11px;font-weight:900;letter-spacing:.06em}.card header b{padding:4px 8px;background:#111;color:#fff}.card.grounded header b{background:#315e9a}.card.unresolved header b{background:#d2471d}.card h2{font-size:26px;line-height:1.15;margin:18px 0}.visual{border-top:2px solid #111;border-bottom:2px solid #111;padding:9px 0;display:flex;justify-content:space-between;font-size:12px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.cols h3{font-size:10px;letter-spacing:.12em}.ev,.alt{border:1.5px solid #111;padding:9px;margin:7px 0}.ev p{font-size:12px;line-height:1.45}.ev small{color:#666}.alt{font-size:11px}.alt span{float:right;color:#666}.card footer{margin-top:12px;font-size:10px;color:#666}.muted{color:#777;font-size:12px}.tablewrap{overflow:auto;background:#fffdf7;border:3px solid #111;margin-top:18px}.tablewrap h2{padding:14px 16px;margin:0;border-bottom:2px solid #111}table{border-collapse:collapse;width:100%;font-size:11px}td,th{border-bottom:1px solid #ccc;padding:8px;text-align:left}th{background:#111;color:white;position:sticky;top:0}.note{margin-top:14px;padding:14px;border:2px solid #111;background:#f6b72b;font-weight:800}@media(max-width:1000px){.grid,.cols{grid-template-columns:1fr}.hero h1{font-size:40px}}</style></head><body><main><section class="hero"><small>CONTENT PLANNER / REVIEW</small><h1>数字を、どのページで<br>どう見せるか。</h1><p>BriefとSource Bundleから、各スライドに使う証拠・可視化・Pattern hint・出典を自動選択。未根拠のActionは無理にデータから生成しません。</p></section><div class="note">facts ${p.sourceSummary?.factCount||0} / tables ${p.sourceSummary?.tableCount||0} / candidates ${p.sourceSummary?.candidateCount||0}</div><section class="grid">${slideCards}</section><section class="tablewrap"><h2>Candidate Catalog</h2><table><thead><tr><th>ID</th><th>Kind</th><th>Title</th><th>Visual</th><th>Supported</th><th>Quality</th><th>Source</th></tr></thead><tbody>${catalog}</tbody></table></section></main></body></html>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
