#!/usr/bin/env node
const fs=require('fs'),path=require('path');
const input=process.argv[2], output=process.argv[3]||'/mnt/data/deck-length-review.v1.html';
if(!input){console.error('usage: node build_deck_length_review_html.js edited-plan.json [output.html]');process.exit(2)}
const p=JSON.parse(fs.readFileSync(input,'utf8')), meta=p.deckLengthEditor||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const opClass=t=>t==='MERGE'?'merge':t==='SPLIT'?'split':'drop';
const ops=(meta.operations||[]).map(o=>`<div class="op ${opClass(o.type)}"><div class="tag">${o.type}</div><b>${esc((o.sourceIds||[]).join(' + '))}</b>${o.resultIds?` → ${esc(o.resultIds.join(' + '))}`:''}<p>${esc(o.reason)}</p></div>`).join('');
const slides=p.slides.map((s,i)=>`<article><div class="n">${String(i+1).padStart(2,'0')}</div><div><small>${esc(s.storyStep)} · ${esc(s.deckLength?.operation||'KEEP')}</small><h3>${esc(s.claim)}</h3><p>${esc(s.question)}</p></div></article>`).join('');
const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><title>Deck Length Editor v1</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f0e7;color:#111;font-family:Arial,'Yu Gothic',sans-serif}.wrap{max-width:1180px;margin:auto;padding:42px}.eyebrow{font-size:12px;letter-spacing:.18em;font-weight:800}.hero{border-top:7px solid #111;padding-top:20px}.hero h1{font-size:52px;line-height:1;margin:12px 0}.counts{display:flex;gap:16px;margin:28px 0}.count{background:#faf8f2;border:2px solid #111;padding:22px;min-width:180px}.count b{font-size:42px}.arrow{font-size:36px;align-self:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}.panel{background:#faf8f2;border:2px solid #111;padding:24px}.op{border-top:3px solid #111;padding:15px 0}.op .tag{display:inline-block;padding:4px 8px;margin-right:8px;font-size:11px;font-weight:800}.merge .tag{background:#d2471d;color:#fff}.split .tag{background:#f6b72b}.drop .tag{background:#111;color:#fff}.op p{margin:7px 0 0;color:#5e5a52}article{display:grid;grid-template-columns:54px 1fr;gap:16px;border-top:1px solid #bbb;padding:18px 0}.n{font-size:26px;font-weight:900}article h3{margin:4px 0;font-size:22px}article p{margin:0;color:#6c675e}small{font-weight:800;letter-spacing:.08em}.foot{margin-top:24px;padding:16px;border-left:6px solid #d2471d;background:#fff}.warn{color:#b33;font-weight:800}</style><div class="wrap"><div class="eyebrow">DECK LENGTH EDITOR / REVIEW</div><section class="hero"><h1>「何枚にするか」も、<br>資料設計の一部にする。</h1><div class="counts"><div class="count"><small>BEFORE</small><br><b>${meta.beforeCount??'-'}</b> slides</div><div class="arrow">→</div><div class="count"><small>AFTER</small><br><b>${meta.afterCount??'-'}</b> slides</div></div></section><div class="grid"><section class="panel"><h2>編集判断</h2>${ops||'<p>変更なし</p>'}</section><section class="panel"><h2>最終ページ構成</h2>${slides}</section></div><div class="foot"><b>安全境界：</b> 数字・根拠・因果レベルは変更しない。自動適用は可逆な DROP / MERGE / SPLIT のみ。${(meta.warnings||[]).length?`<div class="warn">WARN: ${esc(JSON.stringify(meta.warnings))}</div>`:''}</div></div></html>`;
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,html,'utf8');console.log(output);
