#!/usr/bin/env node
const fs=require('fs');
const input=process.argv[2], output=process.argv[3]||'/mnt/data/driver-review.v1.html';
if(!input){console.error('usage: node build_driver_review_html.js driver-bundle.json [output.html]');process.exit(2)}
const b=JSON.parse(fs.readFileSync(input,'utf8'));if(b.profile!=='DRIVER-BUNDLE-v1')throw new Error('profile must be DRIVER-BUNDLE-v1');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=x=>x==='accounting_decomposition'?'会計的分解':x==='association_only'?'関連のみ':x==='descriptive_difference'?'記述差':'要検証';
const cards=b.drivers.map((d,i)=>`<article class="card ${d.priority.toLowerCase()}"><div class="top"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="pill">${esc(d.type)}</span><span class="score">${d.score}</span></div><h2>${esc(d.title)}</h2><p class="msg">${esc(d.message)}</p><div class="meta"><b>${status(d.causalStatus)}</b><span>confidence ${Number(d.confidence).toFixed(2)}</span><span>n=${esc(d.n??'—')}</span></div>${d.path?.length?`<div class="path">${d.path.map(x=>`<span>${esc(x.value)}</span>`).join('<i>→</i>')}</div>`:''}${d.driverMetric?`<div class="driver">driver: <b>${esc(d.driverMetric)}</b></div>`:''}<details><summary>Evidence / Method</summary><pre>${esc(JSON.stringify({evidence:d.evidence,method:d.method,sourceRefs:d.sourceRefs,warnings:d.warnings},null,2))}</pre></details></article>`).join('');
const t=b.target||{};
const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Driver Explorer Review</title><style>
:root{--bg:#f3f0e7;--paper:#faf8f2;--ink:#111;--red:#d2471d;--yellow:#f6b72b;--muted:#6c675e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,"Yu Gothic",sans-serif}.wrap{max-width:1180px;margin:auto;padding:44px 28px 80px}.eyebrow{font-size:12px;letter-spacing:.18em;font-weight:800}.hero{display:grid;grid-template-columns:1.5fr .8fr;gap:24px;align-items:end;border-bottom:4px solid var(--ink);padding-bottom:24px}.hero h1{font-size:48px;line-height:1;margin:10px 0}.target{background:var(--ink);color:white;padding:24px}.target .big{font-size:42px;font-weight:900}.note{color:var(--muted);max-width:850px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:26px}.card{background:var(--paper);border:2px solid var(--ink);padding:20px;min-height:260px}.card.high{border-top:8px solid var(--red)}.card.med{border-top:8px solid var(--yellow)}.top{display:flex;gap:10px;align-items:center}.rank{font-weight:900}.pill{font-size:11px;border:1px solid var(--ink);padding:4px 7px}.score{margin-left:auto;font-size:28px;font-weight:900}.card h2{font-size:24px;margin:14px 0 10px}.msg{line-height:1.55}.meta{display:flex;flex-wrap:wrap;gap:12px;font-size:12px;margin:14px 0}.path{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin:10px 0}.path span{background:#fff;border:1px solid var(--ink);padding:5px 8px}.path i{font-style:normal}.driver{font-size:13px;margin-top:8px}details{margin-top:16px}summary{cursor:pointer;font-weight:700}pre{white-space:pre-wrap;background:#fff;padding:12px;border:1px solid #bbb;font-size:11px;max-height:280px;overflow:auto}@media(max-width:800px){.hero,.grid{grid-template-columns:1fr}.hero h1{font-size:36px}}</style></head><body><div class="wrap"><div class="hero"><div><div class="eyebrow">INSIGHT ENGINE V2 / DRIVER EXPLORER</div><h1>何が動かした可能性があるか。</h1><p class="note">寄与分解・セグメント差・関連を分けて表示します。<b>「関連」から因果を断定しません。</b> 会計的寄与は変化の構成説明であり、業務上の原因証明ではありません。</p></div><div class="target"><small>TARGET METRIC</small><div class="big">${esc(t.label||t.metric)}</div><div>${esc(t.baseline??'')} ${esc(t.baselineValue??'—')} → ${esc(t.current??'')} ${esc(t.currentValue??'—')}</div><div>Δ ${esc(t.delta??'—')} ${esc(t.unit||'')}</div></div></div><section class="grid">${cards}</section></div></body></html>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
