#!/usr/bin/env node
const fs=require('fs');
const briefPath=process.argv[2],planPath=process.argv[3],output=process.argv[4]||'/mnt/data/presentation-plan.causal.v1.json';
if(!briefPath||!planPath){console.error('usage: node build_causal_presentation_plan.js brief.json causal-plan.json [output.json]');process.exit(2)}
const brief=JSON.parse(fs.readFileSync(briefPath,'utf8')),p=JSON.parse(fs.readFileSync(planPath,'utf8'));
if(brief.profile!=='BRIEF-v1'||p.profile!=='CAUSAL-TEST-PLAN-v1')throw new Error('invalid profiles');
const primary=p.recommendation.primary||{};const sec=p.recommendation.secondary||[];const dmap=Object.fromEntries((p.diagnostics||[]).map(d=>[d.id,d]));
const preview=p.effectPreview;const unit=p.dataReadiness;
const diagText=(id,fmt)=>dmap[id]?fmt(dmap[id]):'未確認';
const pretrend=diagText('parallel_pretrend',d=>`${d.value}${d.unit||''}`),smd=diagText('baseline_balance',d=>String(d.value));
const slides=[
 {id:'s01',storyStep:'opening',question:'何を因果検証するのか？',claim:`${p.hypothesis.treatment||'処置'}が${p.hypothesis.outcome||'アウトカム'}を改善したかを検証する`,causalStatus:'hypothesis',confidence:.95,sourceRefs:p.sourceRefs,payload:{title:brief.title||'因果検証設計',lead:`第一候補は ${primary.label||'設計未確定'}。単純前後比較ではなく識別条件を先に確認する。`,label:'PRIMARY DESIGN',metric:primary.label||'—',metricLabel:p.hypothesis.estimand||'ATT'}},
 {id:'s02',storyStep:'kpi',question:'このデータで何ができるか？',claim:`${unit.nTreated}処置 / ${unit.nControl}対照、事前${unit.nPrePeriods}期・事後${unit.nPostPeriods}期で検証可能性を確認`,causalStatus:'design_readiness',confidence:.93,sourceRefs:p.sourceRefs,payload:{title:'識別に必要な4つの土台',metrics:[{value:`${unit.nUnits}`,label:'units',note:`${unit.nTreated} treated / ${unit.nControl} control`},{value:`${unit.nPrePeriods}`,label:'pre periods',note:'平行トレンド確認に使用'},{value:`${unit.nPostPeriods}`,label:'post periods',note:'導入後の動学確認'},{value:preview?`${preview.estimate}${preview.unit||''}`:'—',label:'exploratory DiD',note:'仮定検証前の参考値'}]}},
 {id:'s03',storyStep:'hierarchy',question:'どう識別するか？',claim:`${primary.label||'設計'}は「群差」と「時間差」の差を見る`,causalStatus:'identification_strategy',confidence:.92,sourceRefs:p.sourceRefs,payload:{title:`${primary.label||'Causal design'} の識別ロジック`,stages:[{title:`PRE ${unit.nPrePeriods}期`,text:'導入前の水準と傾きを確認',output:'parallel trend'},{title:`処置 ${unit.nTreated} / 対照 ${unit.nControl}`,text:'同時期の未処置群を比較軸にする',output:'comparison'},{title:`POST ${unit.nPostPeriods}期`,text:'導入後の差の広がりを見る',output:'dynamic effect'},{title:p.hypothesis.estimand||'ATT',text:'差の差を推定',output:'effect + CI'}]}},
 {id:'s04',storyStep:'association',question:'主張前に何を確認するか？',claim:'推定値より先に、識別仮定が壊れていないかを見る',causalStatus:'assumption_check',confidence:.90,sourceRefs:p.sourceRefs,payload:{title:'因果主張の前提を3点で確認',items:[{title:'平行トレンド',text:`事前傾き差 ${pretrend}。Event Studyのleadも確認する。`},{title:'Balance / Overlap',text:`最大 |SMD| ${smd}。AIPW/IPWではpropensity overlapと極端重みを確認。`},{title:'同時施策・波及',text:'導入と同時に棚割・価格・運用変更がないか、近隣店へのspilloverも確認。'}],footnote:'これらが崩れる場合、点推定が出ても「効果」と断定しない。'}},
 {id:'s05',storyStep:'generic',question:'どの推定を組み合わせるか？',claim:`主分析は ${primary.label||'未確定'}。${sec.slice(0,2).map(x=>x.label).join(' と ')||'感度分析'}で結論の安定性を確認する`,causalStatus:'analysis_plan',confidence:.91,sourceRefs:p.sourceRefs,payload:{support:`単純前後比較は主分析にしない。${(p.recommendation.rejected||[]).slice(0,2).map(x=>`${x.label}: ${x.reason}`).join(' / ')}`} },
 {id:'s06',storyStep:'action',question:'次に何を実行するか？',claim:'因果推定は「モデルを回す」より先に、母集団・仮定・判定ルールを固定する',causalStatus:'validation_plan',confidence:.95,sourceRefs:p.sourceRefs,payload:{title:'実行順序を固定する',actions:(p.executionPlan||[]).slice(0,3).map((x,i)=>({what:x.title,who:i===0?'Analyst':i===1?'Business + Analyst':'Analyst',when:['STEP 1','STEP 2','STEP 3'][i]}))}}
];
const out={version:'1.0',profile:'PRESENTATION-PLAN-v1',deck:{title:brief.title||'因果検証設計',topic:brief.topic||p.hypothesis.statement,audience:brief.audience||'executive',objective:'analysis',anchorMetric:p.hypothesis.outcomeField||'',anchorSourceRefs:p.sourceRefs},slides,suppressedEvidence:[],quality:{causalPlanProfile:p.profile,primaryMethod:primary.method,warningCount:(p.warnings||[]).length}};
fs.writeFileSync(output,JSON.stringify(out,null,2),'utf8');console.log(output);
