#!/usr/bin/env node
const fs=require('fs');
const input=process.argv[2],output=process.argv[3]||'/mnt/data/presentation-editor-review.html';
if(!input){console.error('usage: node build_presentation_editor_review_html.js presentation-plan.json [output.html]');process.exit(2)}
const p=JSON.parse(fs.readFileSync(input,'utf8'));if(p.profile!=='PRESENTATION-PLAN-v1')throw new Error('invalid profile');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slides=(p.slides||[]).map((s,i)=>`<article class="card"><div class="num">${String(i+1).padStart(2,'0')}</div><div><div class="step">${esc(s.storyStep)} · ${esc(s.causalStatus||'')}</div><h2>${esc(s.claim)}</h2><p class="q">Q. ${esc(s.question)}</p><div class="meta">sources: ${esc((s.sourceRefs||[]).join(' / ')||'—')} · confidence ${Math.round((s.confidence||0)*100)}%</div>${s.notes?.length?`<ul>${s.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`:''}</div></article>`).join('');
const sup=(p.suppressedEvidence||[]).map(x=>`<tr><td>${esc(x.slideId)}</td><td>${esc(x.title)}</td><td>${esc((x.sourceRefs||[]).join(', '))}</td><td>${esc(x.reason)}</td></tr>`).join('')||'<tr><td colspan="4">なし</td></tr>';
const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Presentation Editor Review</title><style>*{box-sizing:border-box}body{margin:0;background:#efebe2;color:#111;font-family:Inter,'Yu Gothic',sans-serif}.wrap{max-width:1200px;margin:auto;padding:26px}.hero{background:#111;color:#fff;padding:28px;border:3px solid #111}.hero small{letter-spacing:.15em;font-weight:900}.hero h1{font-size:48px;line-height:.95;margin:12px 0}.hero p{max-width:860px;line-height:1.7}.grid{display:grid;gap:12px;margin-top:14px}.card{display:grid;grid-template-columns:70px 1fr;gap:18px;background:#faf8f2;border:2px solid #111;padding:18px}.num{font-size:34px;font-weight:1000;color:#d2471d}.step{font-size:10px;font-weight:1000;letter-spacing:.1em;color:#6c675e}.card h2{font-size:26px;margin:5px 0 8px;line-height:1.2}.q{font-weight:800;margin:0 0 10px}.meta{font-size:10px;color:#6c675e;font-weight:800}.card ul{font-size:11px;line-height:1.5}.supp{background:#faf8f2;border:2px solid #111;padding:18px;margin-top:14px}.supp h2{margin-top:0}.supp table{width:100%;border-collapse:collapse;font-size:11px}.supp th,.supp td{border:1px solid #aaa;padding:8px;text-align:left;vertical-align:top}.pass{display:inline-block;background:#d2471d;color:#fff;font-weight:1000;padding:6px 9px;margin-right:6px}</style></head><body><div class="wrap"><section class="hero"><small>PRESENTATION EDITOR / STORY COMPRESSION</small><h1>${esc(p.deck?.title||'Presentation')}</h1><p>分析結果をそのまま貼らず、1ページ1問・1結論に圧縮。スコープ不明の横断比較、因果を示さない相関、内部メタデータを自動で整理します。</p><div><span class="pass">${(p.slides||[]).length} SLIDES</span><span class="pass">${p.suppressedEvidence?.length||0} SUPPRESSED</span><span class="pass">${esc(p.deck?.anchorMetric||'NO ANCHOR')}</span></div></section><main class="grid">${slides}</main><section class="supp"><h2>抑制した証拠</h2><table><thead><tr><th>Slide</th><th>Evidence</th><th>Source</th><th>Reason</th></tr></thead><tbody>${sup}</tbody></table></section></div></body></html>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
