#!/usr/bin/env node
const fs=require('fs');
const input=process.argv[2],output=process.argv[3]||'/mnt/data/deck-director-review.v2.html';
if(!input){console.error('usage: node build_deck_director_review_html.js directed-plan.json [output.html]');process.exit(2)}
const p=JSON.parse(fs.readFileSync(input,'utf8')),d=p.deckDirector||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const energy={PEAK:100,ANCHOR:72,BRIDGE:58,EVIDENCE:66,CALM:38};
const cards=p.slides.map((s,i)=>{const dd=s.deckDirection||{},v=dd.variants?.A||{};return `<article class="card"><div class="top"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(dd.energy)}</b></div><h2>${esc(s.claim)}</h2><p class="q">${esc(s.question)}</p><div class="meta"><span>${esc(dd.visualMode)}</span><span>${esc(v.pattern)}</span><span>${esc(v.composition)}</span></div><div class="bridge">→ ${esc(dd.continuity?.out)}</div></article>`}).join('');
const curve=p.slides.map((s,i)=>`<div class="barwrap"><div class="bar" style="height:${energy[s.deckDirection?.energy]||40}%"></div><small>${i+1}<br>${esc(s.deckDirection?.energy)}</small></div>`).join('');
const transitions=(d.transitions||[]).map(t=>`<div class="tr"><b>${esc(t.type)}</b><span>${esc(t.cue)}</span></div>`).join('');
const issues=(d.issues||[]).length?(d.issues||[]).map(x=>`<li>${esc(x.severity||'info')} · ${esc(x.type)}</li>`).join(''):'<li>blocking issue なし</li>';
const html=`<!doctype html><meta charset="utf-8"><title>Deck Director v2 Review</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f0e7;color:#111;font-family:Inter,"Noto Sans JP",sans-serif}.wrap{max-width:1500px;margin:auto;padding:48px}header{display:flex;justify-content:space-between;border-bottom:3px solid #111;padding-bottom:24px}.k{font-size:12px;letter-spacing:.18em;color:#6c675e}h1{font-size:44px;margin:8px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:28px}.card{background:#faf8f2;border:2px solid #111;padding:20px;min-height:260px}.top{display:flex;justify-content:space-between;font-size:12px;letter-spacing:.12em}.top b{color:#d2471d}.card h2{font-size:24px;line-height:1.15;margin:28px 0 12px}.q{color:#6c675e;min-height:48px}.meta{display:flex;gap:8px;flex-wrap:wrap}.meta span{border:1px solid #111;padding:5px 8px;font-size:11px}.bridge{border-top:1px solid #111;margin-top:20px;padding-top:14px;font-weight:700;font-size:13px}.panel{margin-top:28px;background:#faf8f2;border:2px solid #111;padding:24px}.curve{height:220px;display:flex;gap:18px;align-items:flex-end;border-bottom:2px solid #111;padding:0 20px}.barwrap{flex:1;height:190px;display:flex;flex-direction:column;justify-content:flex-end;align-items:center}.bar{width:60%;background:#d2471d;border:2px solid #111;min-height:12px}.barwrap small{text-align:center;margin-top:8px}.transitions{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.tr{padding:12px;border-left:5px solid #d2471d;background:#f3f0e7}.tr b,.tr span{display:block}.tr span{font-size:12px;margin-top:6px}.quality{display:grid;grid-template-columns:1fr 1fr;gap:24px}</style><div class="wrap"><header><div><div class="k">DECK DIRECTOR / V2</div><h1>${esc(p.deck?.title||'Deck Review')}</h1></div><div><b>PEAKS</b><br>${esc((d.quality?.peakSlides||[]).join(' / '))}</div></header><section class="grid">${cards}</section><section class="panel"><div class="k">ENERGY CURVE</div><div class="curve">${curve}</div></section><section class="panel"><div class="k">PAGE-TO-PAGE BRIDGES</div><div class="transitions">${transitions}</div></section><section class="panel quality"><div><div class="k">QUALITY</div><pre>${esc(JSON.stringify(d.quality||{},null,2))}</pre></div><div><div class="k">ISSUES / REPAIRS</div><ul>${issues}</ul><pre>${esc(JSON.stringify(d.repairs||[],null,2))}</pre></div></section></div>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
