#!/usr/bin/env node
const fs=require('fs');
const input=process.argv[2],output=process.argv[3]||'/mnt/data/deck-director-review.v3.html';
if(!input){console.error('usage: node build_deck_director_review_html_v3.js directed-plan.json [output.html]');process.exit(2)}
const p=JSON.parse(fs.readFileSync(input,'utf8')),d=p.deckDirector||{};
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const rows=p.slides.map((s,i)=>`<article class="slide"><div class="num">${String(i+1).padStart(2,'0')}</div><div class="meta"><span>${esc(s.storyStep)}</span><span>${esc(s.deckDirection?.energy)}</span><span>${esc(s.deckDirection?.transitionIn)}</span></div><h2>${esc(s.deckDirection?.headline||s.claim)}</h2><p class="q">${esc(s.question)}</p><div class="patterns">A ${esc(s.deckDirection?.patterns?.A||s.deckDirection?.variants?.A?.pattern)} · B ${esc(s.deckDirection?.patterns?.B||s.deckDirection?.variants?.B?.pattern)} · C ${esc(s.deckDirection?.patterns?.C||s.deckDirection?.variants?.C?.pattern)}</div></article>`).join('');
const moveText=(d.moves||[]).length?(d.moves||[]).map(m=>`${m.position}: ${m.from} → ${m.to}`).join(' / '):'順序変更なし';
const html=`<!doctype html><meta charset="utf-8"><title>Deck Director v3 Review</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f0e7;color:#111;font-family:Arial,'Yu Gothic',sans-serif}.wrap{max-width:1240px;margin:auto;padding:40px}.eyebrow{font-size:12px;letter-spacing:.18em}.hero{display:grid;grid-template-columns:1.4fr .6fr;gap:24px;margin:12px 0 28px}.hero h1{font-size:44px;line-height:1.02;margin:0}.panel{background:#faf8f2;border:2px solid #111;padding:18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.slide{background:#faf8f2;border:2px solid #111;padding:20px;min-height:220px;position:relative}.num{font-size:52px;font-weight:800;color:#d2471d}.meta{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}.meta span,.patterns{font-size:11px;letter-spacing:.05em}.slide h2{font-size:24px;line-height:1.15;margin:16px 0 10px}.q{font-size:14px;color:#5d5850}.quality{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.quality div{border-top:5px solid #111;background:#faf8f2;padding:14px}.quality strong{display:block;font-size:24px}</style><div class="wrap"><div class="eyebrow">DECK DIRECTOR v3 / NARRATIVE ORDER + TITLE CHAIN</div><div class="hero"><div><h1>${esc(p.deck?.title||'Deck')}</h1><p>${esc((d.titleSequence||[]).join(' → '))}</p></div><div class="panel"><b>ARC</b><div style="font-size:28px;margin-top:8px">${esc(d.arc||'generic')}</div><p>${esc(moveText)}</p></div></div><div class="quality"><div><span>ORDER VIOLATIONS</span><strong>${esc(d.quality?.orderViolationCountAfter||0)}</strong></div><div><span>MOVED POSITIONS</span><strong>${esc(d.quality?.movedPositionCount||0)}</strong></div><div><span>TRANSITION TYPES</span><strong>${esc(d.quality?.transitionVariety||0)}</strong></div><div><span>ACTION CLOSE</span><strong>${d.quality?.closingAction?'YES':'NO'}</strong></div></div><h3>Final sequence</h3><div class="grid">${rows}</div></div>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
