#!/usr/bin/env node
const fs=require('fs');
const input=process.argv[2],output=process.argv[3]||'/mnt/data/causal-test-review.v1.html';
if(!input){console.error('usage: node build_causal_test_review_html.js plan.json [output.html]');process.exit(2)}
const p=JSON.parse(fs.readFileSync(input,'utf8'));if(p.profile!=='CAUSAL-TEST-PLAN-v1')throw new Error('profile must be CAUSAL-TEST-PLAN-v1');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const chip=(s,t)=>`<span class="chip ${s}">${esc(t)}</span>`;
const diag=(p.diagnostics||[]).map(d=>`<div class="diag"><div>${chip(d.status,d.status.toUpperCase())}<b>${esc(d.label)}</b></div><strong>${esc(d.value)}${esc(d.unit||'')}</strong><p>${esc(d.message)}</p></div>`).join('');
const methods=[p.recommendation?.primary,...(p.recommendation?.secondary||[])].filter(Boolean).map((m,i)=>`<div class="method ${i?'secondary':'primary'}"><div class="rank">${i?'SENSITIVITY':'PRIMARY'}</div><h3>${esc(m.label)}</h3><div class="score">suitability ${esc(m.suitability)}</div><p>${esc(m.reason)}</p></div>`).join('');
const assumptions=(p.assumptions||[]).map(a=>`<tr><td>${esc(a.label)}</td><td>${chip(a.status,a.status)}</td><td>${esc(a.test)}</td><td>${esc(a.failureAction)}</td></tr>`).join('');
const decisions=(p.decisionRules||[]).map(d=>`<div class="decision ${d.status.toLowerCase()}"><b>${esc(d.status)}</b><span>${esc(d.condition)}</span><em>${esc(d.action)}</em></div>`).join('');
const preview=p.effectPreview?`<div class="preview"><div><span>探索的DiD</span><strong>${esc(p.effectPreview.estimate)}${esc(p.effectPreview.unit||'')}</strong></div><p>95% CI ${esc(p.effectPreview.ci95?.[0])} ～ ${esc(p.effectPreview.ci95?.[1])}</p><small>仮定検証前の参考値。これ単独では因果効果として確定しない。</small></div>`:'';
const html=`<!doctype html><meta charset="utf-8"><title>Causal Test Planner Review</title><style>
:root{--bg:#f3f0e7;--paper:#faf8f2;--ink:#111;--accent:#d2471d;--signal:#f6b72b;--muted:#69645d;--line:#c8c2b7}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,"Yu Gothic",Arial,sans-serif}.wrap{max-width:1180px;margin:0 auto;padding:44px}header{border-bottom:4px solid var(--ink);padding-bottom:22px;margin-bottom:26px}.kicker{font-size:12px;font-weight:800;letter-spacing:.15em;color:var(--muted)}h1{font-size:42px;line-height:1.04;margin:12px 0 8px}header p{font-size:18px;font-weight:700;margin:0;color:var(--muted)}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:20px}.card{background:var(--paper);border:2px solid var(--ink);padding:22px}.card h2{font-size:17px;margin:0 0 14px;text-transform:uppercase;letter-spacing:.08em}.methods{display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:12px}.method{border:1.5px solid var(--ink);padding:16px;min-height:158px}.method.primary{background:var(--ink);color:white}.rank{font-size:10px;letter-spacing:.12em;font-weight:900;color:var(--accent)}.primary .rank{color:var(--signal)}.method h3{font-size:24px;margin:12px 0 8px}.method p{font-size:13px;line-height:1.45;margin:8px 0}.score{font-size:12px;font-weight:800}.diags{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.diag{border:1.5px solid var(--ink);padding:14px;background:white;min-height:132px}.diag b{font-size:12px;margin-left:8px}.diag strong{display:block;font-size:26px;margin:16px 0 4px}.diag p{font-size:11px;line-height:1.35;margin:0;color:var(--muted)}.chip{font-size:9px;font-weight:900;border:1px solid currentColor;padding:3px 5px}.good{color:#197346}.caution{color:#9a6a00}.poor{color:#b3261e}.exploratory{color:#315e9a}.unchecked{color:#666}.preview{background:#111;color:white;padding:18px;margin-top:14px}.preview div{display:flex;justify-content:space-between;align-items:end}.preview strong{font-size:42px;color:var(--signal)}.preview p{margin:3px 0}.preview small{color:#ccc}.full{grid-column:1/-1}table{width:100%;border-collapse:collapse;font-size:12px}td,th{border-top:1px solid var(--line);padding:10px;text-align:left;vertical-align:top}th{font-size:10px;letter-spacing:.08em;color:var(--muted)}.decision{display:grid;grid-template-columns:74px 1fr .9fr;gap:16px;padding:12px;border-top:1px solid var(--line);align-items:start}.decision b{font-size:14px}.decision span,.decision em{font-size:12px;line-height:1.4}.decision em{font-style:normal;font-weight:700}.decision.green b{color:#197346}.decision.yellow b{color:#9a6a00}.decision.red b{color:#b3261e}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.meta div{border-left:5px solid var(--accent);background:white;padding:12px}.meta small{display:block;color:var(--muted);font-weight:700}.meta strong{font-size:21px}</style>
<div class="wrap"><header><div class="kicker">CAUSAL TEST PLANNER / REVIEW</div><h1>${esc(p.hypothesis.statement)}</h1><p>相関候補を、そのまま原因と呼ばず「どう検証すれば因果主張に近づけるか」を設計する。</p></header>
<div class="meta"><div><small>UNITS</small><strong>${esc(p.dataReadiness.nUnits)}</strong></div><div><small>TREATED / CONTROL</small><strong>${esc(p.dataReadiness.nTreated)} / ${esc(p.dataReadiness.nControl)}</strong></div><div><small>PRE / POST</small><strong>${esc(p.dataReadiness.nPrePeriods)} / ${esc(p.dataReadiness.nPostPeriods)}</strong></div><div><small>ESTIMAND</small><strong>${esc(p.hypothesis.estimand)}</strong></div></div>
<div class="card full" style="margin-top:20px"><h2>Recommended design</h2><div class="methods">${methods}</div>${preview}</div>
<div class="card full" style="margin-top:20px"><h2>Readiness diagnostics</h2><div class="diags">${diag}</div></div>
<div class="grid" style="margin-top:20px"><div class="card"><h2>Assumptions to validate</h2><table><tr><th>Assumption</th><th>Status</th><th>Test</th><th>If failed</th></tr>${assumptions}</table></div><div class="card"><h2>Decision rules</h2>${decisions}</div></div>
</div>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
