#!/usr/bin/env node
const fs=require('fs'),path=require('path'),cp=require('child_process');
const input=process.argv[2],output=process.argv[3]||'/mnt/data/presentation-plan.directed.v3.json';
if(!input){console.error('usage: node direct_deck_v3.js presentation-plan.json [output.json]');process.exit(2)}
const plan=JSON.parse(fs.readFileSync(input,'utf8'));
if(plan.profile!=='PRESENTATION-PLAN-v1')throw new Error('profile must be PRESENTATION-PLAN-v1');
const rules=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../deck/deck-director-rules.v3.json'),'utf8'));
const v2tool=path.resolve(__dirname,'direct_deck_v2.js');
function runNode(args){const r=cp.spawnSync(process.execPath,args,{encoding:'utf8'});if(r.status!==0)throw new Error((r.stderr||r.stdout||'failed').trim());return (r.stdout||'').trim();}
function norm(s){return String(s||'').replace(/[\s　。、,.・:：!?！？()（）\-→]/g,'').toLowerCase();}
function objectiveArc(deck){const o=String(deck?.objective||'').toLowerCase();return rules.objectiveToArc[o]||'generic';}
function rankMap(template){return new Map(template.map((s,i)=>[s,i]));}
function locked(s){return rules.lockedFields.some(k=>Boolean(s?.[k]||s?.deckDirection?.[k]));}
function transition(prev,cur){if(!prev)return 'OPEN';const pair={'opening->kpi':'QUANTIFY','kpi->hierarchy':'DRILL','hierarchy->breakdown':'DECOMPOSE','breakdown->association':'QUALIFY','association->action':'RESOLVE','opening->breakdown':'DECOMPOSE','breakdown->hierarchy':'DRILL','hierarchy->association':'QUALIFY','kpi->breakdown':'DECOMPOSE','kpi->association':'QUALIFY','breakdown->action':'RESOLVE','hierarchy->action':'RESOLVE','generic->action':'RESOLVE'};return pair[`${prev.storyStep}->${cur.storyStep}`]||'CONTINUE';}
function headlineFor(slide,transitionType){const base=String(slide.claim||slide.payload?.title||'').trim();const lead=rules.headlineLeadByTransition[transitionType]||'';if(!base)return base;if(!lead||base.startsWith(lead))return base;const max=rules.headlineRules.maxCharsJa||46;const candidate=lead+base;return candidate.length<=max?candidate:base;}
function narrativeViolations(slides,ranks){const out=[];for(let i=1;i<slides.length;i++){const a=slides[i-1],b=slides[i];const ra=ranks.has(a.storyStep)?ranks.get(a.storyStep):999;const rb=ranks.has(b.storyStep)?ranks.get(b.storyStep):999;if(rb<ra&&!locked(a)&&!locked(b))out.push({type:'order_inversion',slides:[a.id,b.id],from:`${a.storyStep}->${b.storyStep}`});if(norm(a.question)===norm(b.question))out.push({type:'repeated_question',slides:[a.id,b.id]});if(norm(a.claim)===norm(b.claim))out.push({type:'repeated_claim',slides:[a.id,b.id]});}return out;}
function stableReorder(slides,ranks){const original=slides.map((s,i)=>({...s,__originalIndex:i}));const lockedSlots=new Map();original.forEach((s,i)=>{if(locked(s))lockedSlots.set(i,s);});const movable=original.filter(s=>!locked(s)).sort((a,b)=>{const ra=ranks.has(a.storyStep)?ranks.get(a.storyStep):999;const rb=ranks.has(b.storyStep)?ranks.get(b.storyStep):999;return ra-rb||a.__originalIndex-b.__originalIndex;});const result=[];let m=0;for(let i=0;i<original.length;i++)result.push(lockedSlots.has(i)?lockedSlots.get(i):movable[m++]);return result.map(({__originalIndex,...s})=>s);}
const arc=objectiveArc(plan.deck),template=rules.arcTemplates[arc]||rules.arcTemplates.generic,ranks=rankMap(template);const before=plan.slides.map(s=>s.id),violationsBefore=narrativeViolations(plan.slides,ranks);let reordered=plan.slides;const movableCount=plan.slides.filter(s=>!locked(s)).length;if(violationsBefore.filter(x=>x.type==='order_inversion').length>=rules.reorderThreshold&&movableCount){const candidate=stableReorder(plan.slides,ranks);const moved=candidate.filter((s,i)=>s.id!==plan.slides[i]?.id).length;if(moved/plan.slides.length<=rules.maxAutomaticMovesRatio||plan.slides.length<=6)reordered=candidate;}
const temp=path.join(path.dirname(output),'.deck-director-v3.tmp.json');fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(temp,JSON.stringify({...plan,slides:reordered},null,2),'utf8');const v2out=path.join(path.dirname(output),'.deck-director-v2.tmp.json');runNode([v2tool,temp,v2out]);const directed=JSON.parse(fs.readFileSync(v2out,'utf8'));const repairs=[],titleSequence=[],questionSequence=[];const slides=directed.slides.map((s,i,arr)=>{const prev=arr[i-1],t=transition(prev,s),headline=headlineFor(s,t);if(headline!==s.claim)repairs.push({slide:s.id,type:'headline_bridge',from:s.claim,to:headline,transition:t});titleSequence.push(headline);questionSequence.push(s.question);return {...s,deckDirection:{...(s.deckDirection||{}),profile:'DECK-DIRECTOR-v3',sequenceIndex:i+1,transitionIn:t,headline,sourceClaim:s.claim,arcRole:s.storyStep}};});const after=slides.map(s=>s.id),violationsAfter=narrativeViolations(slides,ranks),moved=after.filter((id,i)=>id!==before[i]).map((id,i)=>({position:i+1,from:before[i],to:id})),transitionTypes=slides.map(s=>s.deckDirection.transitionIn);const quality={...(directed.deckDirector?.quality||{}),arc,reordered:before.join('|')!==after.join('|'),movedPositionCount:moved.length,orderViolationCountBefore:violationsBefore.filter(x=>x.type==='order_inversion').length,orderViolationCountAfter:violationsAfter.filter(x=>x.type==='order_inversion').length,titleChainComplete:titleSequence.every(Boolean),questionChainComplete:questionSequence.every(Boolean),transitionVariety:new Set(transitionTypes).size,closingAction:slides.at(-1)?.storyStep==='action'};const out={...directed,slides,deckDirector:{...(directed.deckDirector||{}),profile:'DECK-DIRECTOR-v3',arc,template,originalOrder:before,finalOrder:after,moves:moved,repairs:[...(directed.deckDirector?.repairs||[]),...repairs],narrativeIssuesBefore:violationsBefore,narrativeIssuesAfter:violationsAfter,titleSequence,questionSequence,transitionSequence:transitionTypes,quality}};fs.writeFileSync(output,JSON.stringify(out,null,2),'utf8');try{fs.unlinkSync(temp);fs.unlinkSync(v2out);}catch{}console.log(output);
