#!/usr/bin/env node
const fs=require('fs');
const path=require('path');
const input=process.argv[2];
const output=process.argv[3] || '/mnt/data/scene-deck.html';
if(!input){console.error('usage: node render_scene_deck_to_html.js scene-deck.json [output.html]');process.exit(2)}
const deck=JSON.parse(fs.readFileSync(input,'utf8'));
if(deck.profile!=='SCENE-DECK-v1' || !Array.isArray(deck.slides)) throw new Error('invalid SCENE-DECK-v1');
const clean=c=>String(c||'000').replace('#','');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function themeFor(s){const k=s.theme||deck.deck?.defaultTheme;return deck.themes?.[k]||{bg:'FFFFFF',ink:'111111',accent:'D2471D',signal:'F6B72B',paper:'FAF8F2',muted:'777777'}}
function color(v,t,f='111111'){if(!v)return clean(f);if(String(v).startsWith('$'))return clean(t[String(v).slice(1)]||f);return clean(v)}
function stylePos(e){return `left:${e.x}%;top:${e.y}%;width:${e.w}%;height:${e.h}%;z-index:${e.z||0}`}
function textEl(e,t){const s=e.style||{};let inner;if(Array.isArray(e.runs)){inner=e.runs.map(r=>{const rs={...s,...(r.style||{})};return `<span style="font-weight:${rs.bold?900:400};font-style:${rs.italic?'italic':'normal'};color:#${color(rs.color,t,t.ink)};font-size:${Number(rs.fontSize||s.fontSize||18)}pt">${esc(r.text)}${r.breakLine?'<br>':''}</span>`}).join('')}else inner=esc(e.text).replace(/\n/g,'<br>');return `<div class="el text" style="${stylePos(e)};font-family:${esc(s.fontFace||s.font||deck.deck?.fonts?.jp||'Yu Gothic')};font-size:${Number(s.fontSize||18)}pt;font-weight:${s.bold?900:400};font-style:${s.italic?'italic':'normal'};color:#${color(s.color,t,t.ink)};text-align:${s.align||'left'};display:flex;align-items:${s.valign==='middle'?'center':s.valign==='bottom'?'flex-end':'flex-start'};justify-content:${s.align==='center'?'center':s.align==='right'?'flex-end':'flex-start'};letter-spacing:${Number(s.charSpacing||0)}px;line-height:${Number(s.lineHeight||1.2)};transform:${s.rotate?`rotate(${Number(s.rotate)}deg)`:'none'}">${inner}</div>`}
function shapeEl(e,t){const s=e.style||{};const br=e.type==='ellipse'?'50%':e.type==='roundRect'?(s.radius||18)+'px':'0';return `<div class="el" style="${stylePos(e)};background:#${color(s.fill,t,t.paper)};border:${Number(s.lineWidth||1)}px solid #${color(s.line,t,t.ink)};border-radius:${br};opacity:${1-Number(s.fillTransparency||0)/100};transform:${s.rotate?`rotate(${Number(s.rotate)}deg)`:'none'}"></div>`}
function lineEl(e,t){const s=e.style||{};const x1=e.x1,y1=e.y1,x2=e.x2,y2=e.y2;const dx=(x2-x1)*16,dy=(y2-y1)*9;const len=Math.sqrt(dx*dx+dy*dy);const ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="el line" style="left:${x1}%;top:${y1}%;width:${len}px;height:${Number(s.lineWidth||1)}px;background:#${color(s.color||s.line,t,t.ink)};transform-origin:0 0;transform:rotate(${ang}deg);z-index:${e.z||0}"></div>`}
function imageEl(e){let src=e.path||'';if(src&&!/^(data:|https?:)/.test(src)){const p=path.isAbsolute(src)?src:path.resolve(path.dirname(input),src);if(fs.existsSync(p)){const ext=path.extname(p).slice(1)||'png';src=`data:image/${ext==='jpg'?'jpeg':ext};base64,${fs.readFileSync(p).toString('base64')}`}}return `<img class="el" src="${esc(src)}" style="${stylePos(e)};object-fit:${e.style?.fit||'contain'};opacity:${1-Number(e.style?.transparency||0)/100}"/>`}
function chartEl(e,t){const s=e.style||{};const cats=e.categories||e.series?.[0]?.labels||[];const ser=e.series||[];const vals=ser.flatMap(x=>x.values||[]).map(Number);const max=Math.max(1,...vals.map(v=>Math.abs(v)));if(e.chartType==='line'){const w=800,h=360;const points=(ser[0]?.values||[]).map((v,i)=>`${(i/Math.max(1,cats.length-1))*w},${h-(Number(v)/max)*h}`).join(' ');return `<div class="el chart" style="${stylePos(e)}"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" width="100%" height="100%"><polyline fill="none" stroke="#${color(s.colors?.[0]||'$accent',t,t.accent)}" stroke-width="6" points="${points}"/></svg></div>`}const values=ser[0]?.values||[];const cols=Array.isArray(s.colors)?s.colors:['$accent'];return `<div class="el chart bars" style="${stylePos(e)};display:flex;align-items:flex-end;gap:2%;padding:3%;border-left:1px solid #${color(s.axisColor||'$ink',t,t.ink)};border-bottom:1px solid #${color(s.axisColor||'$ink',t,t.ink)}">${values.map((v,i)=>`<div style="flex:1;height:${Math.max(2,Math.abs(Number(v))/max*92)}%;background:#${color(cols[i%cols.length]||'$accent',t,t.accent)}"></div>`).join('')}</div>`}
function elHtml(e,t){if(e.visible===false)return'';if(e.type==='text')return textEl(e,t);if(['rect','roundRect','ellipse'].includes(e.type))return shapeEl(e,t);if(['line','connector'].includes(e.type))return lineEl(e,t);if(e.type==='image')return imageEl(e);if(e.type==='chart')return chartEl(e,t);throw new Error('unsupported '+e.type)}
const slides=deck.slides.map(s=>{const t=themeFor(s);return `<section class="slide-wrap"><div class="slide-meta">${esc(s.id)}${s.meta?.pattern?` · ${esc(s.meta.pattern)}`:''}</div><div class="viewport"><div class="canvas" style="background:#${color(s.background||'$bg',t,t.bg)}">${[...s.elements].sort((a,b)=>(a.z||0)-(b.z||0)).map(e=>elHtml(e,t)).join('')}</div></div></section>`}).join('');
const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(deck.deck?.title||'Scene Deck')}</title><style>*{box-sizing:border-box}body{margin:0;background:#e8e5dd;color:#111;font-family:Inter,'Noto Sans JP','Yu Gothic',sans-serif}.app{max-width:1700px;margin:auto;padding:18px}.head{padding:18px 20px;border:2px solid #111;background:#fff;margin-bottom:14px}.head h1{margin:0;font-size:30px}.head p{margin:6px 0 0;font-size:12px}.slide-wrap{background:#fff;border:2px solid #111;margin:0 0 16px}.slide-meta{padding:7px 10px;border-bottom:1px solid #111;font-size:10px;font-weight:800}.viewport{position:relative;width:100%;overflow:hidden;background:#ccc}.canvas{width:1600px;height:900px;position:absolute;left:0;top:0;transform-origin:top left;overflow:hidden}.el{position:absolute}.text{white-space:pre-wrap;overflow:hidden}.line{position:absolute}.chart{position:absolute}</style></head><body><div class="app"><div class="head"><h1>${esc(deck.deck?.title||'Scene Deck')}</h1><p>SCENE-DECK-v1 · fixed 1600×900 canvas · uniform scale only</p></div>${slides}</div><script>function fit(v){const c=v.querySelector('.canvas');const s=v.clientWidth/1600;c.style.transform='scale('+s+')';v.style.height=(900*s)+'px'}const ro=new ResizeObserver(es=>es.forEach(e=>fit(e.target)));document.querySelectorAll('.viewport').forEach(v=>{ro.observe(v);fit(v)});</script></body></html>`;
fs.writeFileSync(output,html,'utf8');console.log(output);
