#!/usr/bin/env node
const fs=require('fs'),path=require('path'),cp=require('child_process'),os=require('os');
const root=path.resolve(__dirname,'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'presentation-editor-'));
const run=(script,args=[])=>{const r=cp.spawnSync(process.execPath,[path.join(root,script),...args],{encoding:'utf8'});if(r.status!==0)throw new Error(`${script}: ${(r.stderr||r.stdout||'failed').trim()}`);return(r.stdout||'').trim()};
const source=path.join(tmp,'source.json'),insight=path.join(tmp,'insight.json'),driver=path.join(tmp,'driver.json'),source2=path.join(tmp,'source2.json'),brief2=path.join(tmp,'brief2.json'),content=path.join(tmp,'content.json'),pres=path.join(tmp,'presentation.json');
run('samples/generate_driver_explorer_sample.js',[source]);
run('tools/analyze_insights.js',[source,insight]);
run('tools/analyze_drivers.js',[source,insight,path.join(root,'samples/brief.driver-explorer.sample.v1.json'),driver]);
run('tools/enrich_source_bundle_with_drivers.js',[source,driver,source2]);
run('tools/apply_driver_bundle_to_brief.js',[path.join(root,'samples/brief.driver-explorer.sample.v1.json'),driver,brief2]);
run('tools/plan_content.js',[brief2,source2,content]);
run('tools/edit_content_for_presentation.js',[brief2,content,driver,pres]);
const p=JSON.parse(fs.readFileSync(pres,'utf8'));
const fail=(m)=>{console.error('FAIL:',m);process.exit(1)};
if(p.profile!=='PRESENTATION-PLAN-v1')fail('profile');
if(p.slides.length!==6)fail('slide count');
const steps=p.slides.map(s=>s.storyStep).join(',');
if(steps!=='opening,kpi,hierarchy,breakdown,association,action')fail('story sequence '+steps);
const k=p.slides.find(s=>s.storyStep==='kpi')?.payload?.metrics||[];
if(k.map(x=>x.value).join('|')!=='+35.5百万円|+27.2百万円|82.2%|r=0.96')fail('kpi values '+k.map(x=>x.value).join('|'));
if(!k.every(x=>String(x.value).length<=24&&!/[。！？!?]/.test(String(x.value))))fail('KPI scalar fit');
const h=p.slides.find(s=>s.storyStep==='hierarchy')?.payload?.stages||[];
if(h.map(x=>x.title).join('→')!=='道東→帯広→生鮮→デリカ')fail('hierarchy path');
const b=p.slides.find(s=>s.storyStep==='breakdown')?.payload?.items||[];
if(b.slice(0,3).map(x=>x.label).join('/')!=='パン/デリカ/農産')fail('breakdown top3');
const a=p.slides.find(s=>s.storyStep==='association');
if(!a||!a.claim.includes('因果はまだ未確認'))fail('association guardrail');
if(p.slides.some(s=>/(原因|影響した|効果が出た|せいで)/.test(s.claim)))fail('causal wording');
if(!(p.suppressedEvidence||[]).some(x=>x.title==='売変金額 trend'&&x.sourceRefs?.includes('sample:monthly_summary')))fail('scope mismatch suppression');
if(!p.quality?.checks?.scalarKpi||!p.quality?.checks?.storyStepsUnique||!p.quality?.checks?.forbiddenCausalTerms)fail('quality checks');
console.log('PASS presentation editor v1');
