#!/usr/bin/env node
const fs=require('fs'),path=require('path');
const input=process.argv[2],output=process.argv[3];
if(!input){console.error('usage: node validate_readability_v1.js scene-deck.json [report.json]');process.exit(2)}
const deck=JSON.parse(fs.readFileSync(input,'utf8'));
function textOf(e){return Array.isArray(e.runs)?e.runs.map(r=>String(r.text||'')).join(''):String(e.text||'')}
function visualChars(s){let n=0;for(const ch of String(s).replace(/\r/g,'')){if(ch==='\n'){n+=2;continue;}if(/\s/.test(ch)){n+=0.25;continue;}n += /[\x00-\x7F]/.test(ch)?0.58:1;}return n}
function capacity(e,size){const wpx=(Number(e.w)||0)*16,hpx=(Number(e.h)||0)*9,fpx=size*96/72;const lh=Number(e.style?.lineHeight||1.15);const cpl=Math.max(1,wpx/(fpx*0.92));const lines=Math.max(1,hpx/(fpx*lh));return cpl*lines*0.82}
function classify(e){const txt=textOf(e).trim(),y=Number(e.y||0),size=Number(e.style?.fontSize||18),id=String(e.id||'');if(/^ED\d{2}-[A-Z]\s*\//.test(txt))return {role:'system_meta',min:8.5};if(y>=88||/^(※|注[:：]?|出典[:：]?|Source[:：]?|SOURCE[:：]?|n\s*=|N\s*=)/.test(txt))return {role:'footnote',min:9.5};if(/title|headline/i.test(id)||size>=22)return {role:'display_title',min:22};const letters=txt.replace(/[^A-Za-z]/g,'');if(txt&&txt.length<=40&&letters&&letters.toUpperCase()===letters&&y<20)return {role:'kicker',min:10};if(txt.length<=18&&!txt.includes('\n'))return {role:'content_label',min:12};return {role:'body',min:14};}
const errors=[],warnings=[],roleCounts={},slideStats=[];let minContentPt=Infinity,minAnyPt=Infinity;
for(const slide of deck.slides||[]){let chars=0,boxes=0;for(const [idx,e] of (slide.elements||[]).entries()){if(e.type!=='text')continue;const txt=textOf(e).trim(),size=Number(e.style?.fontSize||18),id=e.id||`text#${idx+1}`,c=classify(e);roleCounts[c.role]=(roleCounts[c.role]||0)+1;minAnyPt=Math.min(minAnyPt,size);if(c.role==='content_label'||c.role==='body'){minContentPt=Math.min(minContentPt,size);chars+=visualChars(txt);boxes++;}if(size<c.min-1e-9)errors.push({slide:slide.id,element:id,code:'font_below_role_floor',role:c.role,fontPt:size,minPt:c.min,text:txt});if((c.role==='content_label'||c.role==='body')&&txt){const ratio=visualChars(txt)/capacity(e,size);if(ratio>1.25)errors.push({slide:slide.id,element:id,code:'readability_density_overload',role:c.role,loadRatio:+ratio.toFixed(3),text:txt});else if(ratio>1.05)warnings.push({slide:slide.id,element:id,code:'readability_tight_box',role:c.role,loadRatio:+ratio.toFixed(3),text:txt});}}
if(chars>520)warnings.push({slide:slide.id,code:'high_slide_text_density',visualChars:+chars.toFixed(1)});if(boxes>18)warnings.push({slide:slide.id,code:'many_content_text_boxes',count:boxes});slideStats.push({slide:slide.id,visualChars:+chars.toFixed(1),contentTextBoxes:boxes});}
const report={profile:'READABILITY-QA-v1.1',file:input,policy:{systemMetaMinPt:8.5,kickerMinPt:10,footnoteMinPt:9.5,displayTitleMinPt:22,contentLabelMinPt:12,bodyMinPt:14},minAnyPt:Number.isFinite(minAnyPt)?minAnyPt:null,minContentPt:Number.isFinite(minContentPt)?minContentPt:null,roleCounts,slideStats,errors,warnings,pass:errors.length===0};
if(output){fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2),'utf8')}
if(errors.length){console.error(`FAIL: ${errors.length} readability QA errors`);process.exit(1)}
console.log(`PASS: content min ${report.minContentPt}pt / ${warnings.length} warnings`);
